language: node_js
node_js:
    - "4"
    - "6"

before_script:
    - npm install -g grunt-cli

script:
    - grunt lint
    - mocha

after_success:
    - npm install istanbul codecov
    - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov



sudo: false
