language: node_js
node_js:
    - "4"
    - "6"

before_script:
    - npm install -g grunt-cli

script:
    - grunt lint
    - mocha

after_success:
    - npm install istanbul codecov
    - npm run coverage
    - ./node_modules/.bin/codecov

sudo: false
